INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('1user@test.com', '1_User', '567890', '0', '1');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('2user@test.com', '2_User', '567890', '0', '1');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('3user@test.com', '3_User', '567890', '0', '1');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('4user@test.com', '4_User', '567890', '0', '0');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('5user@test.com', '5_User', '567890', '0', '1');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('6user@test.com', '6_User', '567890', '0', '1');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('7user@test.com', '7_User', '567890', '0', '1');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('8user@test.com', 'User_8', '567890', '0', '0');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('9user@test.com', 'User_9', '567890', '0', '2');
INSERT INTO BANK_USER (EMAIL, USER_NAME, PHONE_NUMBER, STATUS, TYPE) VALUES ('10user@test.com', '1_Admin', '567890', '0', '0');

INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('2', '20241220001', '1', '1000', '1');
INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('2', '20241220002', '0', '1000', '0');
INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('4', '20241220003', '1', '1000', '0');
INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('5', '20241220004', '1', '1000', '2');
INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('6', '20241220005', '1', '1000', '0');
INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('8', '20241220006', '1', '1000', '0');
INSERT INTO BANK_ACCOUNT (USER_ID, ACCOUNT_NUMBER, ACCOUNT_TYPE, ACCOUNT_BALANCE, ACCOUNT_STATUS) VALUES ('8', '20241220007', '0', '1000', '1');